apiVersion: apiextensions.k8s.io/v1beta1
kind:       CustomResourceDefinition
metadata:
    name: jwtconfigs.security.cloud.ibm.com
spec:
    group: security.cloud.ibm.com
    versions:
    - name:    v1
      served:  true
      storage: true
    scope: Namespaced
    names:
        plural:   jwtconfigs
        singular: jwtconfig
        kind:     JwtConfig
    validation:
        openAPIV3Schema:
            properties:
                spec:
                    required:
                    - jwksUrl
                    properties:
                        jwksUrl:
                            type:    string
                            pattern: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)'
