apiVersion: apiextensions.k8s.io/v1beta1
kind:       CustomResourceDefinition
metadata:
    name: oidcconfigs.security.cloud.ibm.com
spec:
    group: security.cloud.ibm.com
    versions:
    - name:    v1
      served:  true
      storage: true
    scope: Namespaced
    names:
        plural:   oidcconfigs
        singular: oidcconfig
        kind:     OidcConfig
    validation:
        openAPIV3Schema:
            properties:
                spec:
                    required:
                    - clientId
                    - discoveryUrl
                    properties:
                        authMethod:
                            type:    string
                            enum:
                            - client_secret_basic
                            - client_secret_post
                        clientId:
                            type:      string
                            minLength: 1
                        discoveryUrl:
                            type:    string
                            pattern: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)'
                        clientSecret:
                            type:      string
                            minLength: 1
                        clientSecretRef:
                            type: object
                            properties:
                                name:
                                    type:      string
                                    minLength: 1
                                key:
                                    type:      string
                                    minLength: 1
                            required:
                            - name
                            - key
